language: ruby
rvm:
    - 2.1
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y imagemagick
deploy:
    provider: s3
    access_key_id: AKIAJRMA5YKNJZ4IXPOA
    secret_access_key:
    secure: W/Cfrf39f31i+BYEMD40XdA6uonTYu2rcHAko36Y8T7pCq6n2ILyattiEWXlHYL1IDTxXfHkgsakBWWmPO1lw9bgofUsctILRMiSQUNPhBx4qZjfs645/vqdeBEus4at+3oT/yVHtzfol98IjfxR290E/nkniVrDIKl7f2VFLytsx4qJnlypa5dexELKs56Xm5fdMKYb6PW5CapSNK7MJrC4/zLLlclr19NgY3YOuckcN91Ga3W6CSgZ2E5ojtvyR4/VdrA6/uxGdEjMCC+9jHS/hhfUlupjo3WePBGw52W0MMM2C8Kkr1sMzpPiipBhuR7yn64Zj6eCBkon0ldF63fSW5IbfeP6HRFFglFMvranHzpPtVOTMcVAeS6kZhdGOI5i6oHx5YkFthlYpl2bmMyg1v5H87T6ohQy8yMx8+IpVQoGa5O7WdjeRYO+SqvUfgxUc7HS+IV60wdbjVGjhxzlmPBbhpeFWfhjjdrsrWNejD16HGJYj+0D6Y3P9hTn3qGTUlyTuz/rejzsw5UenHOyXC80qGxMeBOHGX300mcrpeIRKbbYv+enjX+XR0ABbhcxOpDfOH1NBxIRwioKHWuMEXiCnBnZPh37B95ucla9aagnpnXOt26tkgBYMkZB0MM3E9/d8TTJfutpvfFuUyYAmF93L3X4RvXv9aZaAHA=
    bucket: static.9thcircle.it
    skip_cleanup: true
    region: eu-west-1
    acl: public_read
    detect_encoding: true
    on:
        repo: 9thcirclegames/9thcirclegames-assets
        branch: master
